### ISSUE TITLE
Missing devices entires in the output file

### ISSUE THREAD

**Issue by ratnakarreddyg** [zabrewer/FN70489-Scanner#2]
Hello,

 Thanks a lot for this script, I have tried the script and faced some issues. 

1. If any device is not connecting or authenticating then that device IP Address was not added to the output file. Means, only successfully connected devices are showing in the output file(CSV file). 

2. If devices require the "enable" option to login then this script is not working. 

3. If we have more device entires(500+) in the hosts.yaml file then the output was empty, even though script execution completes.

**Comment by zabrewer** [comment]
Hi - yes, I wrote this script quickly given the timeline, holiday, and my travel schedule.  It doesn't contain nearly the amount of error checking and testing that I would normally put into it.  

1. See above, will try to get to this but I'm still traveling
2. adding secret to the YAML file should fix this.  

Example:

- device_type: cisco_ios
  host: 10.0.0.1
  username: 
  password: cisco
  secret: cisco

3. You can try splitting up the device entries into different YAML files - if I can find the time, I will add a job queue where you can tell the script how many tasks to do at once (i.e. SSH connections) for a given queue/pool - this will allow you to split up tasks without splitting up the YAML file

I hope this helps

**Comment by ratnakarreddyg** [comment]
Thank You @zabrewer
